Genericize uml-build and uml-build-stop
git-svn-id: https://nemesis.fprintf.net/svn/uml/uml-tools@297 6a022d3a-3905-0410-ac87-c01684601b3d

diff --git a/uml-tools/uml-build b/uml-tools/uml-build
--- a/uml-tools/uml-build
+++ b/uml-tools/uml-build
@@ -4,11 +4,31 @@
 #
 
 source @PREFIX@/uml-functions.sh
-
 if [ -z "$1" ]; then
 	BUILDDIR="`pwd`"
 else
 	BUILDDIR="$1"
+fi
+
+source ${BUILDDIR}/etc/make.globals
+source ${BUILDDIR}/etc/make.conf
+
+if [ -z "${PORTDIR}" ]; then
+	die "No PORTDIR.  Are /etc/make.globals and /etc/make.conf broken?"
+fi
+if [ -z "${PORTAGE_TMPDIR}" ]; then
+	die "No PORTAGE_TMPDIR.  Are /etc/make.globals and /etc/make.conf broken?"
+fi
+if [ -z "${DISTDIR}" ]; then
+	die "No DISTDIR.  Are /etc/make.globals and /etc/make.conf broken?"
+fi
+
+SCHEDTOOL=$(which schedtool 2>/dev/null)
+echo $SCHEDTOOL
+if [ -n "${SCHEDTOOL}" ]; then
+	CMD="${SCHEDTOOL} -D -e chroot"
+else
+	CMD="chroot"
 fi
 
 # Stop if it was started
@@ -16,11 +36,15 @@ uml-build-stop
 
 # Mount /proc, /usr/portage, /home/portage
 sudo mount -o bind /proc ${BUILDDIR}/proc || die "Mount of /proc failed"
-sudo mount -o bind /usr/portage ${BUILDDIR}/usr/portage || die "Mount of /usr/portage failed"
-sudo mount -o bind /home/portage ${BUILDDIR}/home/portage || die "Mount of /home/portage failed"
+sudo mount -o bind ${PORTDIR} ${BUILDDIR}${PORTDIR} || die "Mount of ${PORTDIR} failed"
+sudo mount -o bind ${PORTAGE_TMPDIR} ${BUILDDIR}${PORTAGE_TMPDIR} || die "Mount of ${PORTAGE_TMPDIR} failed"
+sudo mount -o bind ${DISTDIR} ${BUILDDIR}${DISTDIR} || die "Mount of ${DISTDIR} failed"
 sudo mount -o bind ${BUILDDIR}/../kernel ${BUILDDIR}/usr/src || die "Mount of /usr/src failed"
+for dir in ${PORTDIR_OVERLAY}; do
+	sudo mount -o bind ${dir} ${BUILDDIR}${dir} || die "Mount of ${dir} failed"
+done
 sudo cp /etc/resolv.conf ${BUILDDIR}/etc || die "Couldn't cp /etc/resolv.conf"
 
 # Now, start screen and chroot
 cd ${BUILDDIR}
-screen -S uml-build -t uml-build sudo -H schedtool -D -e chroot ${BUILDDIR} /bin/bash -l
+screen -S uml-build -t uml-build sudo -H ${CMD} ${BUILDDIR} /bin/bash -l
diff --git a/uml-tools/uml-build-stop b/uml-tools/uml-build-stop
--- a/uml-tools/uml-build-stop
+++ b/uml-tools/uml-build-stop
@@ -11,5 +11,25 @@ else
 	BUILDDIR="$1"
 fi
 
-# unmount our shit
-sudo umount ${BUILDDIR}/proc ${BUILDDIR}/usr/portage ${BUILDDIR}/home/portage ${BUILDDIR}/usr/src || die "umounts failed"
+source ${BUILDDIR}/etc/make.globals
+source ${BUILDDIR}/etc/make.conf
+
+if [ -z "${PORTDIR}" ]; then
+	die "No PORTDIR.  Are /etc/make.globals and /etc/make.conf broken?"
+fi
+if [ -z "${PORTAGE_TMPDIR}" ]; then
+	die "No PORTAGE_TMPDIR.  Are /etc/make.globals and /etc/make.conf broken?"
+fi
+if [ -z "${DISTDIR}" ]; then
+	die "No DISTDIR.  Are /etc/make.globals and /etc/make.conf broken?"
+fi
+
+UMOUNT_DIRS="${BUILDDIR}/proc ${BUILDDIR}${PORTDIR} \
+	${BUILDDIR}${PORTAGE_TMPDIR} ${BUILDDIR}${DISTDIR} \
+	${BUILDDIR}/usr/src"
+
+for dir in ${PORTDIR_OVERLAY}; do
+	UMOUNT_DIRS="${UMOUNT_DIRS} ${BUILDDIR}${dir}"
+done
+# unmount stuff that we mounted
+sudo umount ${UMOUNT_DIRS} || die "umounts failed"
